name: Deploy Ghost to Docker Swarm

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and push Ghost image
      run: |
        docker build -t your-username/ghost-app:latest .
        docker push your-username/ghost-app:latest

    - name: Login to Docker Swarm
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SWARM_HOST }}
        username: ${{ secrets.SWARM_USERNAME }}
        password: ${{ secrets.SWARM_PASSWORD }}
        port: ${{ secrets.SWARM_PORT }}
        script: |
          docker stack deploy -c docker-compose.yml ghost-stack
