name: Deploy Server_ram_fetch_app to Docker Swarm

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/server_ram_fetch:latest

    - name: Login to Docker Swarm
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SWARM_HOST }}
        port: ${{ secrets.SWARM_PORT }}
        # private-key: ${{ secrets.SWARM_PRIVATE_KEY }} # Uncomment this line if needed
        script: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/server_ram_fetch:latest
          docker stack deploy -c docker-compose.yml server-ram-fetch-stack

